//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnableGPlayWithPC.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnableGPlayWithPC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   adb\adb.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AdbPath {
            get {
                return ResourceManager.GetString("AdbPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   続行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は動作確認済みのチャレンジパッドではありません。
        ///それでも実行しますか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Not_Benesse_Tab_Desc {
            get {
                return ResourceManager.GetString("Dialog_Not_Benesse_Tab_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チャレンジパッドが見つかりませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Not_Benesse_Tab_Inst {
            get {
                return ResourceManager.GetString("Dialog_Not_Benesse_Tab_Inst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {1} に権限 &quot;{0}&quot; を付与することができませんでした。
        ///アプリは完全に動作しない可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_PermNotGranted_Desc {
            get {
                return ResourceManager.GetString("Dialog_PermNotGranted_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} に権限を付与することができませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_PermNotGranted_Inst {
            get {
                return ResourceManager.GetString("Dialog_PermNotGranted_Inst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   何らかのエラーが発生したためデバイスと通信できませんでした。
        ///
        ///以下を確認してください：
        ///・デバイスの接続
        ///・このPCからのUSBデバッグの許可
        ///
        ///確認してから再実行してください。
        ///取得したデバイス名：{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Process_Error_Adb {
            get {
                return ResourceManager.GetString("Dialog_Process_Error_Adb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   adb.exe が見つかりません。
        ///adb.exe が存在するかどうか確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Process_Error_Adb404 {
            get {
                return ResourceManager.GetString("Dialog_Process_Error_Adb404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} が見つかりません。
        ///そのファイルが存在するかどうか確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Process_Error_File404 {
            get {
                return ResourceManager.GetString("Dialog_Process_Error_File404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理中にエラーが発生しました。
        ///アプリケーションをインストールできませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Process_Error_In {
            get {
                return ResourceManager.GetString("Dialog_Process_Error_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Process_Error_Title {
            get {
                return ResourceManager.GetString("Dialog_Process_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理中にエラーが発生しました。{0}をアンインストールできませんでした。
        ///アンインストールブロッカーが設定されていないこと、デバイス管理者に設定されていないことを確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Process_Error_Un {
            get {
                return ResourceManager.GetString("Dialog_Process_Error_Un", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理中にエラーが発生しました。
        ///何らかのエラーが発生しました。詳しくはアプリケーション開発者にお問い合わせください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Process_Error_Unknown {
            get {
                return ResourceManager.GetString("Dialog_Process_Error_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Google の機能は有効化されました！
        ///デバイスは再起動中です。再起動後使用可能になります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Successed_Desc {
            get {
                return ResourceManager.GetString("Dialog_Successed_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   成功しました！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Successed_Inst {
            get {
                return ResourceManager.GetString("Dialog_Successed_Inst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続されているデバイスが多すぎます。
        ///ひとつのデバイスのみ接続してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_TooManyDevices_Desc {
            get {
                return ResourceManager.GetString("Dialog_TooManyDevices_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続されているデバイスが多すぎます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_TooManyDevices_Inst {
            get {
                return ResourceManager.GetString("Dialog_TooManyDevices_Inst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .apk に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSelector_Extension {
            get {
                return ResourceManager.GetString("FileSelector_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .apk ファイルを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSelector_Title {
            get {
                return ResourceManager.GetString("FileSelector_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン : {0} / Kobold Ver.
        ///
        ///Copyright(c) 2020 AioiLight に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Information_Title {
            get {
                return ResourceManager.GetString("Information_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インストール作業を中止する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotGranted_Cancel {
            get {
                return ResourceManager.GetString("NotGranted_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーを無視して処理を続行する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotGranted_Continue {
            get {
                return ResourceManager.GetString("NotGranted_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   詳細情報を非表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotGranted_HideDetail {
            get {
                return ResourceManager.GetString("NotGranted_HideDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   詳細情報を表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotGranted_ShowDetail {
            get {
                return ResourceManager.GetString("NotGranted_ShowDetail", resourceCulture);
            }
        }
    }
}
